version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26
  coveralls: coveralls/coveralls@1.0.6
  aws-s3: circleci/aws-s3@1.0.11
  browser-tools: circleci/browser-tools@1.0.1
  jq: circleci/jq@2.2.0

commands:
  font_awesome:
    steps:
      - run:
          name: Authenticate FontAwesome
          command: |
            npm config set "@fortawesome:registry" https://npm.fontawesome.com/
            npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME

jobs:
  coveralls:
    executor: cypress/base-14
    steps:
      - attach_workspace:
          at: ~/
      - coveralls/upload:
          parallel_finished: true

workflows:
  test-deploy:
    jobs:
      - cypress/install:
          pre-steps:
            - font_awesome
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 'care ops'
          start: 'npm start'
          post-steps:
            - run: npm run coverage:report:ci
            - coveralls/upload:
                parallel: true
      - coveralls:
          requires:
            - cypress/run

  test_cross_browser:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - cypress/install:
          pre-steps:
            - font_awesome
      - cypress/run:
          pre-steps:
            - browser-tools/install-chrome
            - run: echo 'export CYPRESS_COVERAGE=false' >> $BASH_ENV
          name: Chrome
          browser: chrome
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 'care ops chrome'
          start: 'npm start'
          config: retries=2
      - cypress/run:
          pre-steps:
            - jq/install
            - browser-tools/install-firefox
            - run: echo 'export CYPRESS_COVERAGE=false' >> $BASH_ENV
          name: Firefox
          browser: firefox
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 'care ops firefox'
          start: 'npm start'
          config: retries=2
