version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  codecov: codecov/codecov@1.0.4
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set VersionSuffix
          command: |
            echo "export VERSION_SUFFIX=$(basename $CIRCLE_BRANCH | tr '[:upper:]' '[:lower:]')" >> $BASH_ENV
            source $BASH_ENV
      - aws-s3/sync:
          from: ~/dist
          to: s3://$bucket_name/${VERSION_SUFFIX}
          overwrite: true

workflows:
  test-deploy:
    jobs:
      - cypress/install:
          pre-steps:
            - run:
                name: Set FontAwesome registry URL
                command: 'npm config set "@fortawesome:registry" https://npm.fontawesome.com/'
            - run:
                name: Authenticate with FontAwesome registry
                command: 'npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME'
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 'care ops'
          start: 'npm start'
          post-steps:
            - run: npm run coverage:report:ci
            - codecov/upload:
                file: coverage/lcov.info
      - build:
          requires:
            - cypress/run
      - deploy:
          requires:
            - build
