version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  codecov: codecov/codecov@1.0.4
jobs:
  deploy:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run build
      - run: echo S3 orb stuff for dist/
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build:ci'
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 'care ops'
          post-steps:
            - run: npm run coverage:report:ci
            - codecov/upload:
                file: coverage/lcov.info
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - cypress/run
