version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  report:
    executor: cypress/base-10
    steps:
      - attach_workspace:
        at: ~/
      - run: npm run coverage:report
  deploy:
    executor: cypress/base-10
    steps:
      - attach_workspace:
        at: ~/
      - run: npm run build
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build:ci'
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 'care ops'
      - report:
          requires:
            - cypress/run
      - deploy:
          requires:
            - report
