version: 2.1
orbs:
  cypress: cypress-io/cypress@1.15
  codecov: codecov/codecov@1.0.5
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  pendingPreviewStatus:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: install curl
          command: apk --no-cache add curl
      - run:
          name: Update GitHub status
          command: .circleci/bin/update-gh-status pending

  build:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/
      - run:
          name: Set GitHub status to failure
          command: .circleci/bin/update-gh-status failure
          when: on_fail
  
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set VersionSuffix
          command: |
            echo "export VERSION_SUFFIX=$(echo "$CIRCLE_BRANCH" | tr '[:punct:][:blank:]' '-' | tr '[:upper:]' '[:lower:]')" >> $BASH_ENV
            source $BASH_ENV
            echo "VERSION_SUFFIX set to $VERSION_SUFFIX"
      - aws-s3/sync:
          from: ~/dist
          to: s3://$bucket_name/fe/${VERSION_SUFFIX}
          overwrite: true
      - run:
          name: Set GitHub status to failure
          command: .circleci/bin/update-gh-status failure
          when: on_fail

  addPreviewSubdomainAuth0:
    docker:
      - image: lambci/lambda:build-python3.7
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Add Preview Subdomain to Auth0 configs
          command: |
            source .circleci/bin/auth0_tools
            add_auth0_subdomain "https://fe-"`echo "$CIRCLE_BRANCH" | tr '[:punct:][:blank:]' '-' | tr '[:upper:]' '[:lower:]'`".preview.roundingwell.com"
      - run:
          name: Set GitHub status to failure
          command: .circleci/bin/update-gh-status failure
          when: on_fail
    
  successPreviewStatus:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: install curl
          command: apk --no-cache add curl
      - run:
          name: Update GitHub status
          command: .circleci/bin/update-gh-status success

workflows:
  test-deploy:
    jobs:
      - pendingPreviewStatus
      - cypress/install:
          pre-steps:
            - run:
                name: Set FontAwesome registry URL
                command: 'npm config set "@fortawesome:registry" https://npm.fontawesome.com/'
            - run:
                name: Authenticate with FontAwesome registry
                command: 'npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME'
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 'care ops'
          start: 'npm start'
          post-steps:
            - run: npm run coverage:report:ci
            - codecov/upload:
                file: coverage/lcov.info
      - build:
          requires:
            - cypress/install
      - deploy:
          requires:
            - build
      - addPreviewSubdomainAuth0:
          requires:
            - deploy
      - successPreviewStatus:
          requires:
            - addPreviewSubdomainAuth0
