version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26
  coveralls: coveralls/coveralls@1.0.6
  aws-s3: circleci/aws-s3@1.0.11
  browser-tools: circleci/browser-tools@1.0.1
  jq: circleci/jq@2.2.0

commands:
  font_awesome:
    steps:
      - run:
          name: Authenticate FontAwesome
          command: |
            npm config set "@fortawesome:registry" https://npm.fontawesome.com/
            npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME

  gh_update:
    parameters:
      status:
        type: string
      when:
        type: string
        default: on_success
    steps:
      - run:
          name: Set GitHub status to << parameters.status >>
          command: .circleci/bin/update-gh-status << parameters.status >>
          when: << parameters.when >>

jobs:
  pendingPreviewStatus:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: install curl
          command: apk --no-cache add curl
      - gh_update:
          status: "pending"

  build:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: cd ~/project && npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/
      - gh_update:
          status: "failure"
          when: on_fail

  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Set VersionSuffix
          command: |
            echo "export VERSION_SUFFIX=$(echo "$CIRCLE_BRANCH" | tr '[:punct:][:blank:]' '-' | tr '[:upper:]' '[:lower:]')" >> $BASH_ENV
            source $BASH_ENV
            echo "VERSION_SUFFIX set to $VERSION_SUFFIX"
      - aws-s3/sync:
          from: ~/dist
          to: s3://$bucket_name/fe/${VERSION_SUFFIX}
          overwrite: true
      - gh_update:
          status: "failure"
          when: on_fail

  addPreviewSubdomainAuth0:
    docker:
      - image: lambci/lambda:build-python3.7
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Add Preview Subdomain to Auth0 configs
          command: |
            source .circleci/bin/auth0_tools
            add_auth0_subdomain "https://fe-"`echo "$CIRCLE_BRANCH" | tr '[:punct:][:blank:]' '-' | tr '[:upper:]' '[:lower:]'`".preview.roundingwell.com"
      - gh_update:
          status: "failure"
          when: on_fail

  successPreviewStatus:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - run:
          name: install curl
          command: apk --no-cache add curl
      - gh_update:
          status: "success"

  coveralls:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - coveralls/upload:
          parallel_finished: true

workflows:
  test-deploy:
    jobs:
      - pendingPreviewStatus
      - cypress/install:
          pre-steps:
            - font_awesome
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 'care ops'
          start: 'npm start'
          post-steps:
            - run: npm run coverage:report:ci
            - coveralls/upload:
                parallel: true
      - coveralls:
          requires:
            - cypress/run
      - build:
          requires:
            - cypress/install
      - deploy:
          requires:
            - build
      - addPreviewSubdomainAuth0:
          requires:
            - deploy
      - successPreviewStatus:
          requires:
            - addPreviewSubdomainAuth0

  test_cross_browser:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - cypress/install:
          pre-steps:
            - font_awesome
      - cypress/run:
          pre-steps:
            - browser-tools/install-chrome
          name: Chrome
          browser: chrome
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 'care ops chrome'
          start: 'npm start'
      - cypress/run:
          pre-steps:
            - jq/install
            - browser-tools/install-firefox
          name: Firefox
          browser: firefox
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 'care ops firefox'
          start: 'npm start'
